version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
