apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "instabug.fullname" . }}
  labels:
    {{- include "instabug.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}